server:
  port: 8098
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: deckOfCards    
  datasource:
    url: jdbc:h2:mem:gamedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  